#
parameters:
  name: ''
  BuildPlatform: x86 # ARM, x86, x64
  UseRNFork: true

jobs:
  - job: ${{ parameters.name }}
    displayName: E2E Test
    dependsOn: Setup
    condition: ne( dependencies.Setup.outputs['checkPayload.shouldSkipPRBuild'], 'True' )

    # E2ETest is in the pipeline of windows-vs-pr, but windows-vs-pr is still using vs2017.yml
    # E2ETest can only be executed on windows-2019 or above, so force to use windows-2019 image and override vs2017.yml variables
    # so pool and variables are hard coded here.
    pool:
      vmImage: windows-2019
    variables: 
      VsComponents: Microsoft.VisualStudio.Component.VC.v141.x86.x64,Microsoft.VisualStudio.ComponentGroup.UWP.VC.v141
      BaseIntDir: $(BUILD_SOURCESDIRECTORY)\vnext\build
      VmImage: windows-2019

    timeoutInMinutes: 60 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

    steps:
      - checkout: self
        clean: false
        submodules: false

      - template: prepare-env.yml
        parameters:
          useRnFork: ${{ parameters.UseRNFork }}
          vsComponents: $(VsComponents)
          yarnBuildCmd: build

      - task: NuGetCommand@2
        displayName: NuGet restore - ReactUWPTestApp
        inputs:
          command: restore
          restoreSolution: packages/E2ETest/windows/ReactUWPTestApp.sln
          verbosityRestore: Detailed # Options: quiet, normal, detailed

      - task: CmdLine@2
        displayName: Create bundle
        inputs:
          script: yarn run bundle
          workingDirectory: packages/E2ETest
          
      - task: CmdLine@2
        displayName: run-windows
        inputs:
          script: react-native run-windows --no-packager --arch ${{ parameters.BuildPlatform }} --release --logging
          workingDirectory: packages/E2ETest

      - task: PublishBuildArtifacts@1
        condition:  succeededOrFailed()
        timeoutInMinutes: 10
        inputs:    
          pathtoPublish: packages/E2ETest/msbuild.binlog 
          artifactName: 'ReactUWPTestApp build log' 
          publishLocation: 'Container'

      - task: CopyFiles@2
        displayName: Copy ReactUWPTestApp artifacts
        inputs:
          sourceFolder: $(Build.SourcesDirectory)/packages/E2ETest/windows/ReactUWPTestApp
          targetFolder: $(Build.StagingDirectory)/ReactUWPTestApp
          contents: AppPackages\**
        condition: succeededOrFailed()

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact:ReactUWPTestApp"
        inputs:
          artifactName: ReactUWPTestApp
          pathtoPublish: $(Build.StagingDirectory)/ReactUWPTestApp
        condition: succeededOrFailed()

      # Wait for app to launch. A workaround to avoid WinAppDriver error: Failed to locate opened application window with appId
      - task: PowerShell@2
        displayName: Wait for app to launch
        inputs:
          targetType: inline # filePath | inline
          script: |
            Start-Sleep -Seconds 30

      - task: PowerShell@2
        displayName: 'Check TestApp'
        inputs:
          targetType: 'inline'
          script: 'if ((Get-Process React*) -eq $Null) { echo "TestApp is not running"; exit 1}'

      - task: CmdLine@2
        displayName: run test
        inputs:
          script: yarn run test
          workingDirectory: packages/E2ETest

      - task: CopyFiles@2
        displayName: Copy tree dump output files
        inputs:
          sourceFolder: $(LocalAppData)\Packages\ReactUWPTestApp_kc2bncckyf4ap\LocalState
          targetFolder: $(Build.StagingDirectory)/ReactUWPTestAppTreeDump
          contents: TreeDump\**
        condition: succeededOrFailed()   
        
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact:ReactUWPTestAppTreeDump"
        inputs:
          artifactName: ReactUWPTestAppTreeDump
          pathtoPublish: $(Build.StagingDirectory)/ReactUWPTestAppTreeDump
        condition: succeededOrFailed()       

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "packages/E2ETest/reports/*.log"
        condition: succeededOrFailed()

      - task: PowerShell@2
        displayName: "Show appium log"
        inputs:
          targetType: "inline"
          script: "Get-Content packages/E2ETest/reports/appium.txt | foreach {Write-Output $_}"
        condition: failed()
